version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://0.0.0.0:3001
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    environment:
      - DATABASE_URL=file:/data/database.db
      - JWT_SECRET=zgbYGVmU4obRjwbPNdaweacTjZVMZn8Nux3Q4esSF8pdwo7PEWjjYvWjdvXswCyh
      - FRONT_URL=http://0.0.0.0:3000
    ports:
      - 3001:3001
    volumes:
      - database_data:/data
    networks:
      - app_network

networks:
  app_network:
    external: true

volumes:
  database_data:
